spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: fossep
    url: jdbc:postgresql://localhost:5432/fossepbd
    password: ATBBJAxDDpGx8J6kuJWhrASTqZ4r0BA08016
  jpa:
    open-in-view: 'true'
    generate-ddl: 'false'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: 'false'
  application:
    name: ms-security
server:
  port: '8080'

